# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - chess-psp

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.209'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chess-psp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_630567db862c4928b0aa082ab97ab0b6 }}
        package: ${{env.DOTNET_ROOT}}/myapp 
